version: '3.8'

services:
  python-api:
    build: ./python-api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  rust-api:
    build: ./rust-api
    ports:
      - "8001:8001"
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped