# docker-compose.yml
services:
  # Train model first
  model-trainer:
    build:
      context: .
      dockerfile: model/Dockerfile
    volumes:
      - ./model:/app/output
    command: sh -c "python train_model.py && cp *.onnx *.json /app/output/"
    profiles: ["training"]

  # Python API
  python-api:
    build: ./python-api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model:ro
    environment:
      - PYTHONPATH=/app

  # Rust API
  rust-api:
    build: ./rust-api
    ports:
      - "8001:8001"
    volumes:
      - ./model:/app/model:ro

  # Benchmarking service
  benchmark:
    build:
      context: .
      dockerfile: benchmarks/Dockerfile
    volumes:
      - ./benchmarks/results:/app/results
      - ./model:/app/model:ro
    depends_on:
      - python-api
      - rust-api
    profiles: ["benchmark"]
    command: python benchmark.py

  concurrent-test:
    build:
      context: .
      dockerfile: benchmarks/Dockerfile
    volumes:
      - ./benchmarks/results:/app/results
      - ./model:/app/model:ro
    depends_on:
      - python-api
      - rust-api
    profiles: ["concurrent-test"]
    command: python concurrent_load_test.py

  wrk-test:
    build:
      context: ./benchmarks
      dockerfile: wrk.Dockerfile
    depends_on:
      - python-api
      - rust-api
    profiles: ["wrk-test"]